"use client";
import { useActionState } from "react";
import { createServiceBookingAction } from "@/app/service-actions";

export function BookingForm({ service }: { service: { id: string; name: string; basePrice: number } }) {
  const [state, action, pending] = useActionState(createServiceBookingAction, {});
  return <form action={action} className="grid gap-4 md:grid-cols-2"><input type="hidden" name="serviceId" value={service.id} /><div className="md:col-span-2 border-l-4 border-brand bg-[#FFF5F4] p-4"><p className="font-bold text-ink">{service.name}</p><p className="mt-1 text-sm text-[#667085]">From £{service.basePrice.toLocaleString("en-GB")}. Your preferred time is confirmed by our team.</p></div><Field name="carMake" label="Vehicle make" required /><Field name="carModel" label="Vehicle model" required /><Field name="carRegistration" label="Registration" /><Field name="postcode" label="Postcode" required /><div className="md:col-span-2"><Field name="addressLine1" label="Address line 1" required /></div><Field name="addressLine2" label="Address line 2 (optional)" /><Field name="city" label="City" required /><Field name="preferredDate" label="Preferred date" type="date" required /><Field name="preferredTime" label="Preferred time" type="time" required /><div className="md:col-span-2"><label className="mb-1.5 block text-sm font-bold">Notes (optional)</label><textarea name="notes" rows={4} className="w-full rounded-md border border-[#D0D5DD] p-3" /></div>{state.error && <p className="md:col-span-2 text-sm font-bold text-[#B42318]" role="alert">{state.error}</p>}<button disabled={pending} className="md:col-span-2 rounded-md bg-brand px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{pending ? "Submitting…" : "Request booking"}</button></form>;
}
function Field({ name, label, required, type = "text" }: { name: string; label: string; required?: boolean; type?: string }) { return <div><label htmlFor={name} className="mb-1.5 block text-sm font-bold">{label}</label><input id={name} name={name} type={type} required={required} min={type === "date" ? new Date().toISOString().slice(0, 10) : undefined} className="w-full rounded-md border border-[#D0D5DD] p-3" /></div>; }
