"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { createClient } from "@/lib/supabase/client";
type ImageRow = { id: string; storage_path: string; sort_order: number; is_primary: boolean; url: string | null };
export function ImageManager({ carId, userId, images }: { carId: string; userId: string; images: ImageRow[] }) { const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null); async function upload(files: FileList | null) { if (!files) return; const selected = Array.from(files); if (images.length + selected.length > 12) return setMessage("A listing can contain up to 12 images."); if (selected.some((file) => !["image/jpeg", "image/png", "image/webp"].includes(file.type) || file.size > 10 * 1024 * 1024)) return setMessage("Use JPEG, PNG or WebP images up to 10MB."); setPending(true); setMessage(null); const supabase = createClient(); for (const [index, file] of selected.entries()) { const extension = file.type.split("/")[1] === "jpeg" ? "jpg" : file.type.split("/")[1]; const path = `${userId}/${carId}/${crypto.randomUUID()}.${extension}`; const { error: storageError } = await supabase.storage.from("car-images").upload(path, file, { contentType: file.type, upsert: false }); if (storageError) { setMessage("An image upload failed. Please try again."); break; } const { error: recordError } = await supabase.from("car_images").insert({ car_id: carId, storage_path: path, sort_order: images.length + index, is_primary: images.length === 0 && index === 0 }); if (recordError) { await supabase.storage.from("car-images").remove([path]); setMessage("Image metadata failed; the uploaded file was removed."); break; } } setPending(false); router.refresh(); }
 async function remove(image: ImageRow) { setPending(true); setMessage(null); const supabase = createClient(); const { error: storageError } = await supabase.storage.from("car-images").remove([image.storage_path]); if (storageError) setMessage("Storage removal failed. The image record was kept so you can retry."); else { const { error } = await supabase.from("car_images").delete().eq("id", image.id); if (error) setMessage("The file was removed but its record could not be updated. Please contact support."); } setPending(false); router.refresh(); }
 async function makePrimary(image: ImageRow) { setPending(true); const { error } = await createClient().rpc("set_primary_car_image", { p_image_id: image.id }); if (error) setMessage("Unable to set the primary image."); setPending(false); router.refresh(); }
 async function move(image: ImageRow, direction: "up" | "down") { setPending(true); const { error } = await createClient().rpc("move_car_image", { p_image_id: image.id, p_direction: direction }); if (error) setMessage("Unable to reorder images."); setPending(false); router.refresh(); }
 return <section className="mt-8 border-t border-[#E4E7EC] pt-6"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Vehicle images</h2><p className="mt-1 text-sm text-[#667085]">Up to 12 JPEG, PNG or WebP images, 10MB each.</p></div><label className="cursor-pointer rounded-md border border-[#D0D5DD] px-4 py-2 text-sm font-bold"><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" disabled={pending} onChange={(event) => upload(event.target.files)} />{pending ? "Working…" : "Upload images"}</label></div>{message && <p role="alert" className="mt-3 text-sm font-bold text-[#B42318]">{message}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-3">{images.map((image) => <div key={image.id} className="border border-[#E4E7EC] p-2">{image.url ? <div className="relative aspect-[4/3]"><Image src={image.url} alt="Vehicle upload" fill unoptimized className="object-cover" /></div> : <div className="grid aspect-[4/3] place-items-center bg-[#F5F6F7] text-xs text-[#667085]">Image unavailable</div>}<div className="mt-2 flex items-center justify-between gap-2 text-xs"><button disabled={pending} onClick={() => move(image, "up")} className="font-bold text-[#475467]">↑</button>{image.is_primary ? <span className="font-bold text-[#15803D]">Primary</span> : <button disabled={pending} onClick={() => makePrimary(image)} className="font-bold text-brand">Make primary</button>}<button disabled={pending} onClick={() => move(image, "down")} className="font-bold text-[#475467]">↓</button><button disabled={pending} onClick={() => remove(image)} className="font-bold text-[#B42318]">Remove</button></div></div>)}</div></section>; }
