import { ChevronDown, CirclePlus, Clock3, Pencil, PoundSterling } from "lucide-react";
import { AdminPageHeader, AdminStatus, adminButton, adminInput } from "@/components/admin/admin-ui";
import { requireRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import { saveServiceTypeAction } from "@/app/service-actions";

type Service = { id: string; name: string; slug: string; description: string; short_description: string | null; base_price: number; estimated_duration_minutes: number | null; is_active: boolean };

export default async function AdminServicesPage() {
  await requireRole("admin");
  const supabase = await createClient();
  const { data: services } = await supabase.from("service_types").select("*").order("name");
  const active = services?.filter((service) => service.is_active).length ?? 0;
  return <main className="mx-auto max-w-[1440px] p-5 sm:p-8">
    <AdminPageHeader eyebrow="Service catalogue" title="Mobile services" description="Create, price, and control the services customers can book." action={<AdminStatus tone="green">{active} public services</AdminStatus>} />
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-5 sm:px-6"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-red-50 text-[#d92d20]"><CirclePlus size={19} /></span><div><h2 className="font-bold text-[#0b1f33]">Create a service</h2><p className="text-sm text-slate-500">Add a new offering to the public booking catalogue.</p></div></div></div><div className="p-5 sm:p-6"><ServiceTypeForm /></div></section>
    <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#d92d20]">Catalogue</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-[#0b1f33]">Existing services</h2></div><p className="text-sm font-medium text-slate-500">{services?.length ?? 0} total</p></div><div className="mt-5 space-y-3">{services?.length ? services.map((service) => <details key={service.id} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-5 sm:px-6"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-[#0b1f33]">{service.name}</h3><AdminStatus tone={service.is_active ? "green" : "slate"}>{service.is_active ? "Public" : "Hidden"}</AdminStatus></div><p className="mt-1 truncate text-sm text-slate-500">{service.short_description || "No short description added"}</p></div><div className="flex shrink-0 items-center gap-5 text-sm text-slate-500"><span className="hidden items-center gap-1.5 sm:flex"><PoundSterling size={15} />{Number(service.base_price).toLocaleString("en-GB")}</span><span className="hidden items-center gap-1.5 md:flex"><Clock3 size={15} />{service.estimated_duration_minutes ?? "—"} min</span><ChevronDown size={18} className="transition group-open:rotate-180" /></div></summary><div className="border-t border-slate-100 bg-slate-50/70 p-5 sm:p-6"><div className="mb-5 flex items-center gap-2 text-sm font-bold text-slate-700"><Pencil size={16} /> Edit service</div><ServiceTypeForm service={service} /></div></details>) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white py-14 text-center text-sm text-slate-500">No services have been created yet.</div>}</div></section>
  </main>;
}

function ServiceTypeForm({ service }: { service?: Service }) { return <form action={async (form) => { "use server"; await saveServiceTypeAction(form); }} className="grid gap-5 md:grid-cols-2">{service && <input type="hidden" name="id" value={service.id} />}<Field name="name" label="Service name" value={service?.name} required /><Field name="slug" label="URL slug" value={service?.slug} required /><Field name="basePrice" label="Base price (£)" value={service?.base_price} type="number" required /><Field name="estimatedDurationMinutes" label="Estimated duration (minutes)" value={service?.estimated_duration_minutes} type="number" /><div className="md:col-span-2"><Field name="shortDescription" label="Short description" value={service?.short_description ?? ""} /></div><div className="md:col-span-2"><label className="mb-1.5 block text-sm font-bold text-slate-700">Full description</label><textarea name="description" required defaultValue={service?.description} rows={4} className={`${adminInput} resize-y`} /></div><div className="flex flex-wrap items-center justify-between gap-4 md:col-span-2"><label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input name="isActive" type="checkbox" defaultChecked={service?.is_active ?? true} className="h-4 w-4 rounded border-slate-300 accent-[#d92d20]" />Visible in public catalogue</label><button className={adminButton}>{service ? "Save changes" : "Create service"}</button></div></form>; }
function Field({ name, label, value, type = "text", required }: { name: string; label: string; value?: string | number | null; type?: string; required?: boolean }) { return <div><label className="mb-1.5 block text-sm font-bold text-slate-700">{label}</label><input name={name} type={type} required={required} defaultValue={value ?? ""} min={type === "number" ? 0 : undefined} className={adminInput} /></div>; }
