"use client";
import { useActionState, useState, useTransition } from "react";
import { MailCheck, RotateCw } from "lucide-react";
import { registerAction, resendConfirmationAction, type AuthFormState } from "@/app/auth/actions";
const initialState: AuthFormState = {};
export function RegisterForm() {
  const [state, action, pending] = useActionState(registerAction, initialState);
  const [resendState, setResendState] = useState<AuthFormState>({});
  const [isResending, startResend] = useTransition();
  const confirmationEmail = state.confirmationEmail ?? resendState.confirmationEmail;
  if (confirmationEmail) return <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-center"><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-white text-emerald-700 shadow-sm"><MailCheck size={23} /></span><h3 className="mt-4 text-lg font-bold text-[#0b1f33]">Check your email</h3><p className="mt-2 text-sm leading-6 text-slate-600">We sent a confirmation link to <span className="font-bold text-slate-800">{confirmationEmail}</span>. You must confirm your email before signing in.</p>{resendState.error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-medium text-red-700">{resendState.error}</p>}{resendState.success && <p role="status" className="mt-4 text-sm font-medium text-emerald-700">{resendState.success}</p>}<button type="button" disabled={isResending} onClick={() => startResend(async () => setResendState(await resendConfirmationAction(confirmationEmail)))} className="mt-5 inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 shadow-sm transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60"><RotateCw size={16} className={isResending ? "animate-spin" : ""} />{isResending ? "Sending…" : "Resend confirmation email"}</button></div>;
  return <form action={action} className="space-y-4" noValidate><Input id="fullName" label="Full name" autoComplete="name" placeholder="Your full name" /><Input id="email" label="Email address" type="email" autoComplete="email" placeholder="you@example.com" /><Input id="phone" label="UK phone number" type="tel" autoComplete="tel" placeholder="07123 456789" /><Input id="password" label="Password" type="password" autoComplete="new-password" placeholder="At least 8 characters" minLength={8} /><Input id="confirmPassword" label="Confirm password" type="password" autoComplete="new-password" placeholder="Repeat your password" minLength={8} />{state.error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-medium text-red-700">{state.error}</p>}<button disabled={pending} className="w-full rounded-xl bg-[#d92d20] px-5 py-3.5 text-sm font-bold text-white shadow-sm transition hover:bg-[#b42318] disabled:cursor-not-allowed disabled:opacity-60">{pending ? "Creating account…" : "Create free account"}</button><p className="text-center text-xs leading-5 text-slate-400">By continuing, you agree to use Shaz responsibly.</p></form>;
}
function Input({ id, label, type = "text", autoComplete, placeholder, minLength }: { id: string; label: string; type?: string; autoComplete: string; placeholder: string; minLength?: number }) { return <div><label htmlFor={id} className="mb-2 block text-sm font-bold text-slate-700">{label}</label><input id={id} name={id} type={type} autoComplete={autoComplete} required minLength={minLength} placeholder={placeholder} className="auth-input !pl-4" /></div>; }
