import { CheckCircle2, Droplets, PackagePlus, Store } from "lucide-react";
import { requireRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import { AdminPageHeader, AdminStatus, adminButton, adminInput } from "@/components/admin/admin-ui";
import { createSupplierAction, saveOilFitmentAction, saveOilProductAction, saveSupplierAction } from "./actions";

export default async function AdminOilsPage() {
  await requireRole("admin");
  const supabase = await createClient();
  const [{ data: suppliers }, { data: products }, { data: fitments }] = await Promise.all([
    supabase.from("suppliers").select("*").order("name"),
    supabase.from("oil_products").select("*").order("brand").order("name"),
    supabase.from("oil_fitments").select("id,make,model,year_from,year_to,fuel_type,is_primary,verified_at,source_reference,oil_products(brand,name,viscosity_grade)").order("created_at", { ascending: false }),
  ]);

  return <main className="mx-auto max-w-[1440px] p-5 sm:p-8">
    <AdminPageHeader eyebrow="Oil operations" title="Oil catalogue & fitments" description="Add supplier products and publish a recommendation only after its vehicle fitment has been verified." action={<AdminStatus tone={fitments?.some((item) => item.verified_at) ? "green" : "amber"}>{fitments?.filter((item) => item.verified_at).length ?? 0} verified matches</AdminStatus>} />

    <section className="mt-7 grid gap-6 xl:grid-cols-2">
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-[#e94a3f]"><Store size={19} /></span><div><h2 className="font-bold text-[#082a30]">Supplier setup</h2><p className="text-sm text-slate-500">Keep a supplier prospective until the local trade agreement is confirmed.</p></div></div>{suppliers?.map((supplier) => <form key={supplier.id} action={saveSupplierAction} className="mt-6 grid gap-4 border-t border-slate-100 pt-6 sm:grid-cols-2"><input type="hidden" name="id" value={supplier.id} /><p className="sm:col-span-2 text-sm font-bold text-[#082a30]">{supplier.name}</p><Field name="contactName" label="Contact name" value={supplier.contact_name} /><Field name="contactEmail" label="Email" value={supplier.contact_email} type="email" /><Field name="contactPhone" label="Phone" value={supplier.contact_phone} /><div><label className="mb-1.5 block text-sm font-bold text-slate-700">Status</label><select name="status" defaultValue={supplier.status} className={adminInput}><option value="prospective">Prospective</option><option value="active">Active</option><option value="paused">Paused</option></select></div><div className="sm:col-span-2"><label className="mb-1.5 block text-sm font-bold text-slate-700">Ordering notes</label><textarea name="orderingNotes" rows={3} defaultValue={supplier.ordering_notes ?? ""} className={`${adminInput} resize-y`} /></div><div className="sm:col-span-2"><button className={adminButton}>Save supplier</button></div></form>)}<details className="mt-6 border-t border-slate-100 pt-5"><summary className="cursor-pointer text-sm font-bold text-[#e94a3f]">Add another supplier</summary><form action={createSupplierAction} className="mt-5 grid gap-4 sm:grid-cols-2"><Field name="name" label="Supplier name" required /><div><label className="mb-1.5 block text-sm font-bold text-slate-700">Status</label><select name="status" defaultValue="prospective" className={adminInput}><option value="prospective">Prospective</option><option value="active">Active</option><option value="paused">Paused</option></select></div><Field name="contactName" label="Contact name" /><Field name="contactEmail" label="Email" type="email" /><Field name="contactPhone" label="Phone" /><div className="sm:col-span-2"><label className="mb-1.5 block text-sm font-bold text-slate-700">Ordering notes</label><textarea name="orderingNotes" rows={3} className={`${adminInput} resize-y`} placeholder="Branch, account reference, collection process…" /></div><div className="sm:col-span-2"><button className={adminButton}>Add supplier</button></div></form></details></div>

      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-50 text-[#e94a3f]"><PackagePlus size={19} /></span><div><h2 className="font-bold text-[#082a30]">Add oil product</h2><p className="text-sm text-slate-500">Use the exact supplier SKU, pack size and approvals.</p></div></div><form action={saveOilProductAction} className="mt-6 grid gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-sm font-bold text-slate-700">Supplier</label><select name="supplierId" className={adminInput}><option value="">No supplier</option>{suppliers?.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></div><Field name="supplierSku" label="Supplier SKU" /><Field name="brand" label="Brand" required /><Field name="name" label="Product name" required /><Field name="viscosityGrade" label="Viscosity (e.g. 5W-30)" required /><Field name="volumeLitres" label="Pack size (litres)" type="number" required step="0.01" /><Field name="price" label="Customer price (£)" type="number" required step="0.01" /><Field name="specifications" label="Approvals (comma-separated)" /><Field name="imageUrl" label="Product image URL" type="url" /><div className="sm:col-span-2"><Field name="description" label="Description" /></div><label className="flex items-center gap-2 text-sm font-semibold text-slate-700 sm:col-span-2"><input type="checkbox" name="isActive" className="accent-[#e94a3f]" />Available to customers</label><div className="sm:col-span-2"><button className={adminButton}>Add oil product</button></div></form></div>
    </section>

    <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#082a30] text-white"><Droplets size={19} /></span><div><h2 className="font-bold text-[#082a30]">Add verified vehicle fitment</h2><p className="text-sm text-slate-500">Customers only see rows marked verified. Add the partner catalogue or manufacturer reference.</p></div></div>{products?.length ? <form action={saveOilFitmentAction} className="mt-6 grid gap-4 md:grid-cols-3"><div><label className="mb-1.5 block text-sm font-bold text-slate-700">Oil product</label><select name="oilProductId" required className={adminInput}><option value="">Choose product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.brand} {product.name} · {product.viscosity_grade}</option>)}</select></div><Field name="make" label="Vehicle make" required /><Field name="model" label="Vehicle model" required /><Field name="yearFrom" label="Year from" type="number" /><Field name="yearTo" label="Year to" type="number" /><div><label className="mb-1.5 block text-sm font-bold text-slate-700">Fuel type</label><select name="fuelType" className={adminInput}><option value="">Any</option>{["petrol","diesel","hybrid","plug_in_hybrid","electric"].map((fuel) => <option key={fuel} value={fuel}>{fuel.replaceAll("_", " ")}</option>)}</select></div><Field name="engineMin" label="Engine cc from" type="number" /><Field name="engineMax" label="Engine cc to" type="number" /><Field name="sourceReference" label="Verification source" /><div className="md:col-span-3"><Field name="notes" label="Internal notes" /></div><div className="flex flex-wrap gap-6 md:col-span-3"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="isPrimary" className="accent-[#e94a3f]" />Primary recommendation</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="isVerified" className="accent-[#e94a3f]" />Fitment verified</label></div><div className="md:col-span-3"><button className={adminButton}>Add fitment</button></div></form> : <p className="mt-6 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Add an oil product before creating vehicle fitments.</p>}</section>

    <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#e94a3f]">Current data</p><h2 className="mt-1 text-2xl font-bold text-[#082a30]">Products and fitments</h2></div><p className="text-sm text-slate-500">{products?.length ?? 0} products · {fitments?.length ?? 0} fitments</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{fitments?.map((fitment) => <article key={fitment.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-[#082a30]">{fitment.make} {fitment.model}</h3><p className="mt-1 text-sm text-slate-500">{fitment.year_from ?? "Any"}–{fitment.year_to ?? "Any"} · {fitment.fuel_type?.replaceAll("_", " ") ?? "Any fuel"}</p></div>{fitment.verified_at ? <AdminStatus tone="green"><CheckCircle2 size={13} /> Verified</AdminStatus> : <AdminStatus tone="amber">Draft</AdminStatus>}</div><p className="mt-4 border-t border-slate-100 pt-4 text-sm font-semibold">{fitment.oil_products?.brand} {fitment.oil_products?.name} · {fitment.oil_products?.viscosity_grade}</p>{fitment.source_reference && <p className="mt-2 text-xs text-slate-500">Source: {fitment.source_reference}</p>}</article>)}</div></section>
  </main>;
}

function Field({ name, label, value, type = "text", required, step }: { name: string; label: string; value?: string | number | null; type?: string; required?: boolean; step?: string }) {
  return <div><label className="mb-1.5 block text-sm font-bold text-slate-700">{label}</label><input name={name} type={type} required={required} defaultValue={value ?? ""} step={step} className={adminInput} /></div>;
}
