"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireRole, requireUser } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
const f=(x:FormData,k:string)=>String(x.get(k)??"").trim(); const post=/^[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}$/i;
export async function createVerificationAction(_: {error?:string}, form:FormData){await requireUser(); const date=f(form,"date"); if(!post.test(f(form,"postcode"))||!date||date<new Date().toISOString().slice(0,10))return{error:"Enter a valid UK postcode and a future preferred date."}; const s=await createClient(); const {data,error}=await s.rpc("create_verification_request",{p_car_id:f(form,"carId")||null as never,p_registration:f(form,"registration"),p_make:f(form,"make"),p_model:f(form,"model"),p_year:f(form,"year")?Number(f(form,"year")):null as never,p_seller_name:f(form,"sellerName"),p_seller_phone:f(form,"sellerPhone"),p_address:f(form,"address"),p_city:f(form,"city"),p_postcode:f(form,"postcode"),p_preferred_date:date,p_preferred_time:f(form,"time"),p_notes:f(form,"notes")||undefined}); if(error||!data)return{error:"We could not submit this inspection request."}; redirect(`/dashboard/verifications/${data}`)}
export async function verificationAdmin(id:string,action:"confirm"|"finalise"){await requireRole("admin");const s=await createClient();const r=action==="confirm"?await s.rpc("confirm_verification_request",{p_id:id}):await s.rpc("finalise_verification",{p_id:id});if(r.error)return{error:"Unable to update this request."};revalidatePath("/admin/verifications");revalidatePath(`/cars/${id}`)}
export async function assignVerification(id:string,form:FormData){await requireRole("admin");const s=await createClient();await s.rpc("assign_verification_inspector",{p_id:id,p_inspector:f(form,"inspector")});revalidatePath("/admin/verifications");revalidatePath("/inspector")}
export async function scheduleVerification(id:string,form:FormData){await requireRole("admin");const s=await createClient();await s.rpc("schedule_verification_inspection",{p_id:id,p_scheduled_for:f(form,"scheduledFor")});revalidatePath("/admin/verifications");revalidatePath("/inspector")}
export async function startInspection(id:string){await requireRole("inspector");const s=await createClient();await s.rpc("start_verification_inspection",{p_id:id});revalidatePath("/inspector")}
export async function saveReport(id:string,form:FormData){await requireRole("inspector");const s=await createClient();const q=(k:string)=>f(form,k) as never;const r=await s.rpc("save_inspection_report",{p_request_id:id,p_result:q("result"),p_summary:f(form,"summary"),p_notes:f(form,"notes"),p_body:q("body"),p_tyres:q("tyres"),p_interior:q("interior"),p_engine:q("engine"),p_brakes:q("brakes"),p_mileage_checked:form.get("mileage")==="on",p_registration_checked:form.get("registrationChecked")==="on"});if(r.error)return{error:"Unable to save the report."};if(form.get("submit")==="yes")await s.rpc("submit_inspection_report",{p_request_id:id});revalidatePath("/inspector");return{success:"Report saved."}}
