import Image from "next/image";
import Link from "next/link";
import { CarCard } from "@/components/cars/car-card";
import { SearchControls } from "@/components/cars/search-controls";
import { ServiceCard } from "@/components/services/service-card";
import { Button } from "@/components/ui/button";
import { SectionHeading } from "@/components/ui/section-heading";
import { makes } from "@/lib/mock-data";
import { getHomepageCars } from "@/lib/marketplace/cars";
import { getActiveServices } from "@/lib/services/services";

export default async function HomePage() {
  const [browseCars, featuredCars, services] = await Promise.all([getHomepageCars(), getHomepageCars(true), getActiveServices(4)]);
  return <>
    <section className="border-b border-[#E4E7EC] bg-[#F5F6F7]"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 lg:grid-cols-[1.35fr_.65fr] lg:px-8 lg:py-12"><div><p className="text-sm font-bold uppercase tracking-[.12em] text-brand">UK used cars</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight text-ink sm:text-5xl">Find your next car</h1><p className="mt-3 max-w-2xl text-base leading-7 text-[#667085]">Browse used vehicles from sellers across the UK. Search by make, model, postcode and price.</p><div className="mt-6 border border-[#D0D5DD] bg-white p-4 shadow-sm sm:p-5"><SearchControls compact /></div></div><div className="relative hidden min-h-56 overflow-hidden lg:block"><Image src="https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1000&q=85" alt="Car driving on an open road" fill priority sizes="30vw" className="object-cover" /></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-11 lg:px-8"><SectionHeading eyebrow="Recently added" title="Browse used cars" link={{ href: "/cars", label: "View all cars" }} />{browseCars.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{browseCars.map((car) => <CarCard key={car.id} car={car} />)}</div> : <div className="mt-6 border border-dashed border-[#D0D5DD] p-8 text-center text-[#667085]">New listings will appear here soon.</div>}</section>
    <section className="border-y border-[#E4E7EC] bg-[#F5F6F7]"><div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><SectionHeading eyebrow="Find by manufacturer" title="Popular makes" /><div className="mt-6 grid grid-cols-3 border-l border-t border-[#E4E7EC] sm:grid-cols-5 lg:grid-cols-8">{makes.map((make) => <Link href={`/cars?make=${make}`} key={make} className="border-b border-r border-[#E4E7EC] bg-white px-3 py-4 text-center text-sm font-bold text-[#344054] hover:bg-[#FFF5F4] hover:text-brand">{make}</Link>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-11 lg:px-8"><div className="border-l-4 border-[#F59E0B] bg-[#FFFAEB] px-5 py-4"><SectionHeading eyebrow="Selected listings" title="Featured cars" copy="A distinct selection of quality used cars worth a closer look." link={{ href: "/cars", label: "See all listings" }} /></div>{featuredCars.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{featuredCars.map((car) => <CarCard key={car.id} car={car} />)}</div> : <div className="mt-6 border border-dashed border-[#D0D5DD] p-8 text-center text-[#667085]">Featured listings will appear here soon.</div>}</section>
    <section className="bg-ink"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-10 text-white sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[.12em] text-[#F97066]">Sell your car</p><h2 className="mt-2 text-3xl font-bold">Ready to sell your car?</h2><p className="mt-2 text-[#D0D5DD]">List your vehicle and connect with interested buyers.</p></div><Button href="/sell-car">Sell My Car</Button></div></section>
    <section className="border-b border-[#E4E7EC] bg-[#F5F6F7]"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-12 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div className="relative min-h-72 overflow-hidden border border-[#E4E7EC]"><Image src="https://images.unsplash.com/photo-1625047509248-ec889cbff17f?auto=format&fit=crop&w=1200&q=85" alt="Inspector reviewing a vehicle" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover" /></div><div><p className="text-sm font-bold uppercase tracking-[.12em] text-brand">Vehicle verification</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-ink sm:text-4xl">Buy with confidence</h2><p className="mt-3 text-lg font-semibold text-[#344054]">Not sure about a car?</p><p className="mt-2 max-w-xl leading-7 text-[#667085]">Have one of our inspectors visit the vehicle before you buy. They check the car in person and produce a clear report for your decision.</p><ul className="mt-5 grid gap-3 text-sm font-semibold text-[#344054] sm:grid-cols-2">{["Physical vehicle visit", "Condition checks", "Inspection photos", "Inspection report", "Verified vehicle status"].map((item) => <li key={item} className="border-l-2 border-[#16A34A] pl-3">{item}</li>)}</ul><Button href="/verification" className="mt-6">Request Vehicle Verification</Button></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-11 lg:px-8"><SectionHeading eyebrow="Mobile car services" title="We come to you" copy="Book a location and a qualified worker travels to your car. No physical garage visit required." link={{ href: "/services", label: "View all services" }} />{services.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map((service) => <ServiceCard key={service.slug} service={service} />)}</div> : <div className="mt-6 border border-dashed border-[#D0D5DD] p-8 text-center text-[#667085]">Mobile services will be available soon.</div>}</section>
    <section className="border-t border-[#E4E7EC] bg-[#F5F6F7]"><div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><SectionHeading eyebrow="Buying made straightforward" title="How it works" /><div className="mt-6 grid gap-4 md:grid-cols-3">{[["01", "Find a car", "Search vehicles by the details and location that work for you."], ["02", "Check the details", "Review mileage, fuel type, transmission and service history."], ["03", "Contact the seller", "Ask questions and arrange the next step directly with the seller."]].map(([number, title, text]) => <div className="border border-[#E4E7EC] bg-white p-5" key={number}><p className="font-bold text-brand">{number}</p><h3 className="mt-3 text-xl font-bold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-[#667085]">{text}</p></div>)}</div></div></section>
  </>;
}
