import { createClient } from "@/lib/supabase/server";
import { formatGBP } from "@/lib/format";

export type CarCardData = { id: string; title: string; price: string; mileage: string; fuel: string; transmission: string; city: string; image: string | null; verified: boolean; featured: boolean; status?: string; createdAt?: string; registration?: string | null };
export type CarDetailData = CarCardData & { sellerId: string; verifiedAt: string | null; make: string; model: string; variant: string | null; year: number; bodyType: string | null; engineSize: string | null; colour: string | null; postcode: string; registration: string | null; description: string; motExpiry: string | null; serviceHistory: string | null; ulezCompliant: boolean | null; ownersCount: number | null; rejectionReason: string | null; images: string[] };

function enumLabel(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
async function signed(path: string | null) { if (!path) return null; const supabase = await createClient(); const { data } = await supabase.storage.from("car-images").createSignedUrl(path, 600); return data?.signedUrl ?? null; }
async function toCard(row: { id: string; make: string; model: string; variant: string | null; year: number; price: number; mileage: number; fuel_type: string; transmission: string; city: string; is_verified: boolean; is_featured: boolean; status: string; created_at: string; registration?: string | null; car_images: { storage_path: string; is_primary: boolean }[] | null }): Promise<CarCardData> { const image = row.car_images?.find((item) => item.is_primary)?.storage_path ?? row.car_images?.[0]?.storage_path ?? null; return { id: row.id, title: `${row.year} ${row.make} ${row.model}${row.variant ? ` ${row.variant}` : ""}`, price: formatGBP(row.price), mileage: `${row.mileage.toLocaleString("en-GB")} miles`, fuel: enumLabel(row.fuel_type), transmission: enumLabel(row.transmission), city: row.city, image: await signed(image), verified: row.is_verified, featured: row.is_featured, status: row.status, createdAt: row.created_at, registration: row.registration }; }

export async function browseCars(params: Record<string, string | string[] | undefined>) { const supabase = await createClient(); const page = Math.max(1, Number(params.page ?? 1) || 1); const perPage = 12; let query = supabase.from("cars").select("id, make, model, variant, year, price, mileage, fuel_type, transmission, city, is_verified, is_featured, status, created_at, car_images(storage_path,is_primary)", { count: "exact" }).eq("status", "active"); const one = (key: string) => typeof params[key] === "string" ? params[key] : undefined; const make = one("make"); const model = one("model"); const postcode = one("postcode"); if (make) { const terms = make.split(/\s+/).filter(Boolean).map(t => t.replace(/[%_,]/g, "")); for (const term of terms) { query = query.or(`make.ilike.%${term}%,model.ilike.%${term}%,variant.ilike.%${term}%`); } } if (model) query = query.ilike("model", `%${model}%`); if (postcode) query = query.ilike("postcode", `${postcode.replace(/[%_]/g, "")}%`); for (const [key, column, op] of [["minPrice", "price", "gte"], ["maxPrice", "price", "lte"], ["minYear", "year", "gte"], ["maxYear", "year", "lte"], ["maxMileage", "mileage", "lte"]] as const) { const strVal = one(key); if (strVal) { const value = Number(strVal); if (Number.isFinite(value) && value >= 0) query = query[op](column, value); } } const fuel = one("fuel"); const transmission = one("transmission"); const bodyType = one("bodyType"); const city = one("city"); if (fuel) query = query.eq("fuel_type", fuel as never); if (transmission) query = query.eq("transmission", transmission as never); if (bodyType) query = query.ilike("body_type", `%${bodyType}%`); if (city) query = query.ilike("city", `%${city}%`); const sort = one("sort"); if (sort === "price_asc") query = query.order("price", { ascending: true }); else if (sort === "price_desc") query = query.order("price", { ascending: false }); else if (sort === "mileage") query = query.order("mileage", { ascending: true }); else query = query.order("published_at", { ascending: false }); const { data, error, count } = await query.range((page - 1) * perPage, page * perPage - 1); if (error) throw new Error("Unable to load cars."); return { cars: await Promise.all((data ?? []).map(toCard)), count: count ?? 0, page, perPage }; }
export async function getCar(id: string): Promise<CarDetailData | null> { const supabase = await createClient(); const { data, error } = await supabase.from("cars").select("*, car_images(storage_path,is_primary,sort_order)").eq("id", id).maybeSingle(); if (error || !data) return null; const card = await toCard(data); const imageRows = [...(data.car_images ?? [])].sort((a, b) => a.sort_order - b.sort_order); return { ...card, sellerId: data.seller_id, verifiedAt: data.verified_at, make: data.make, model: data.model, variant: data.variant, year: data.year, bodyType: data.body_type, engineSize: data.engine_size ? `${data.engine_size}L` : null, colour: data.colour, postcode: data.postcode, registration: data.registration, description: data.description, motExpiry: data.mot_expiry, serviceHistory: data.service_history, ulezCompliant: data.ulez_compliant, ownersCount: data.owners_count, rejectionReason: data.rejection_reason, images: (await Promise.all(imageRows.map((image) => signed(image.storage_path)))).filter((image): image is string => Boolean(image)) }; }
export async function getHomepageCars(featured = false) { const supabase = await createClient(); let query = supabase.from("cars").select("id, make, model, variant, year, price, mileage, fuel_type, transmission, city, is_verified, is_featured, status, created_at, car_images(storage_path,is_primary)").eq("status", "active").order("published_at", { ascending: false }).limit(4); if (featured) query = query.eq("is_featured", true); const { data, error } = await query; if (error) throw new Error("Unable to load marketplace cars."); return Promise.all((data ?? []).map(toCard)); }
export async function getMyCars() { const supabase = await createClient(); const { data, error } = await supabase.from("cars").select("id, make, model, variant, year, price, mileage, fuel_type, transmission, city, is_verified, is_featured, status, created_at, registration, car_images(storage_path,is_primary)").order("created_at", { ascending: false }); if (error) throw new Error("Unable to load your listings."); return Promise.all((data ?? []).map(toCard)); }
