import { requireRole } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import { assignWorkerAction, cancelBookingAsAdminAction, confirmBookingAction } from "@/app/service-actions";

export default async function AdminBookingsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  await requireRole("admin");
  const { status } = await searchParams;
  const supabase = await createClient();
  const statuses = ["pending", "confirmed", "assigned", "on_the_way", "in_progress", "completed", "cancelled"] as const;
  let query = supabase.from("service_bookings").select("id,customer_id,car_make,car_model,city,postcode,preferred_date,preferred_time,status,quoted_price,created_at,service_types(name),employee_assignments(employee_id,status,profiles!employee_assignments_employee_id_fkey(full_name))").order("created_at", { ascending: false });
  if (typeof status === "string" && (statuses as readonly string[]).includes(status)) query = query.eq("status", status as typeof statuses[number]);
  const [{ data: bookings }, { data: workers }] = await Promise.all([query, supabase.rpc("get_admin_staff_directory")]);
  const activeWorkers = workers?.filter((worker) => worker.staff_status === "active") ?? [];

  return <main className="mx-auto max-w-7xl px-5 py-10 lg:px-8">
    <p className="text-sm font-bold uppercase tracking-[.12em] text-brand">Administration</p><h1 className="mt-2 text-3xl font-bold">Mobile service bookings</h1>
    <div className="mt-5 flex flex-wrap gap-2 text-sm font-bold">{["all", ...statuses].map((item) => <a key={item} href={item === "all" ? "/admin/bookings" : `/admin/bookings?status=${item}`} className="border border-[#D0D5DD] px-3 py-2 capitalize hover:border-brand">{item.replaceAll("_", " ")}</a>)}</div>
    {bookings?.length ? <div className="mt-6 space-y-4">{bookings.map((booking) => <article key={booking.id} className="border border-[#E4E7EC] bg-white p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h2 className="font-bold">{booking.service_types?.name ?? "Mobile service"} · {booking.car_make} {booking.car_model}</h2><p className="mt-1 text-sm text-[#667085]">{booking.city}, {booking.postcode} · Preferred {booking.preferred_date} at {booking.preferred_time}</p><p className="mt-1 text-sm font-bold capitalize text-brand">{booking.status.replaceAll("_", " ")} · £{Number(booking.quoted_price).toLocaleString("en-GB")}</p></div><div className="text-sm text-[#667085]">{booking.employee_assignments?.find((assignment) => assignment.status === "assigned" || assignment.status === "in_progress")?.profiles?.full_name ?? "Unassigned"}</div></div><div className="mt-4 flex flex-wrap items-center gap-3">{booking.status === "pending" && <form action={async () => { "use server"; await confirmBookingAction(booking.id); }}><button className="rounded-md bg-ink px-4 py-2 text-sm font-bold text-white">Confirm</button></form>}{["confirmed", "assigned"].includes(booking.status) && <form action={async (form) => { "use server"; await assignWorkerAction(booking.id, form); }} className="flex gap-2"><select name="workerId" required defaultValue="" className="border border-[#D0D5DD] px-3 text-sm"><option value="" disabled>{activeWorkers.length ? "Assign worker" : "No active workers"}</option>{activeWorkers.map((worker) => <option key={worker.id} value={worker.id}>{worker.full_name || worker.email || "Field worker"} — {worker.email || "Email unavailable"}</option>)}</select><button disabled={!activeWorkers.length} className="border border-brand px-4 py-2 text-sm font-bold text-brand disabled:opacity-50">Assign</button></form>}{["pending", "confirmed", "assigned"].includes(booking.status) && <form action={async () => { "use server"; await cancelBookingAsAdminAction(booking.id); }}><button className="border border-[#B42318] px-4 py-2 text-sm font-bold text-[#B42318]">Cancel</button></form>}</div></article>)}</div> : <div className="mt-6 border border-dashed border-[#D0D5DD] p-10 text-center text-[#667085]">No bookings in this queue.</div>}
  </main>;
}
