alter table public.verification_requests
  add column external_make text,
  add column external_model text,
  add column external_year integer check (external_year is null or external_year between 1886 and extract(year from current_date)::integer + 1),
  add column notes text check (notes is null or char_length(notes) <= 3000),
  add column confirmed_at timestamptz,
  add column scheduled_for timestamptz,
  add column inspection_started_at timestamptz,
  add column report_submitted_at timestamptz,
  add column completed_at timestamptz,
  add column cancelled_at timestamptz,
  add column cancellation_reason text check (cancellation_reason is null or char_length(cancellation_reason) <= 1000);
alter table public.cars add column verified_at timestamptz, add column verified_verification_request_id uuid references public.verification_requests(id) on delete set null;
alter table public.inspection_reports alter column overall_result drop not null, alter column summary drop not null, alter column inspector_id drop not null;
alter table public.inspection_report_images add column evidence_expires_at timestamptz;
create index verification_requests_status_scheduled_idx on public.verification_requests(status, scheduled_for);
create index inspection_report_images_expires_idx on public.inspection_report_images(evidence_expires_at) where evidence_expires_at is not null;

create or replace function public.create_verification_request(p_car_id uuid, p_registration text, p_make text, p_model text, p_year integer, p_seller_name text, p_seller_phone text, p_address text, p_city text, p_postcode text, p_preferred_date date, p_preferred_time time, p_notes text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid; v_car public.cars%rowtype;
begin
 if auth.uid() is null or p_preferred_date < current_date or trim(p_address)='' or trim(p_city)='' or trim(p_postcode) !~* '^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$' then raise exception 'Invalid verification request'; end if;
 if p_car_id is not null then select * into v_car from public.cars where id=p_car_id and status='active'; if not found or v_car.seller_id=auth.uid() then raise exception 'This listing cannot be requested'; end if;
 insert into public.verification_requests(requested_by,car_id,seller_name,seller_phone,vehicle_registration,inspection_address,city,postcode,preferred_date,preferred_time,notes) values(auth.uid(),p_car_id,coalesce(nullif(trim(p_seller_name),''),'Listing seller'),coalesce(nullif(trim(p_seller_phone),''),''),coalesce(v_car.registration,nullif(trim(p_registration),'')),p_address,p_city,upper(trim(p_postcode)),p_preferred_date,p_preferred_time,p_notes) returning id into v_id;
 else
 if trim(p_registration)='' or trim(p_seller_name)='' or trim(p_seller_phone)='' or trim(p_make)='' or trim(p_model)='' then raise exception 'External vehicle details are required'; end if;
 insert into public.verification_requests(requested_by,seller_name,seller_phone,vehicle_registration,inspection_address,city,postcode,preferred_date,preferred_time,external_make,external_model,external_year,notes) values(auth.uid(),trim(p_seller_name),trim(p_seller_phone),trim(p_registration),p_address,p_city,upper(trim(p_postcode)),p_preferred_date,p_preferred_time,trim(p_make),trim(p_model),p_year,p_notes) returning id into v_id;
 end if; return v_id;
end; $$;
create function public.cancel_own_verification_request(p_id uuid,p_reason text default null) returns void language plpgsql security definer set search_path='' as $$ begin update public.verification_requests set status='cancelled',cancelled_at=now(),cancellation_reason=nullif(trim(p_reason),'') where id=p_id and requested_by=auth.uid() and status in ('pending','confirmed'); if not found then raise exception 'Request cannot be cancelled'; end if; end; $$;
create function public.confirm_verification_request(p_id uuid) returns void language plpgsql security definer set search_path='' as $$ begin if not(select private.is_admin()) then raise exception 'Admin access required'; end if; update public.verification_requests set status='confirmed',confirmed_at=now() where id=p_id and status='pending'; if not found then raise exception 'Pending request not found'; end if; end; $$;
create function public.assign_verification_inspector(p_id uuid,p_inspector uuid) returns void language plpgsql security definer set search_path='' as $$ begin if not(select private.is_admin()) or not exists(select 1 from public.profiles where id=p_inspector and role='inspector') then raise exception 'Invalid assignment'; end if; if not exists(select 1 from public.verification_requests where id=p_id and status in ('confirmed','assigned')) then raise exception 'Request must be confirmed'; end if; update public.employee_assignments set status='cancelled' where verification_request_id=p_id and status in ('assigned','accepted','in_progress'); insert into public.employee_assignments(verification_request_id,employee_id,assigned_by,status) values(p_id,p_inspector,auth.uid(),'assigned'); update public.verification_requests set status='assigned' where id=p_id; end; $$;
create function public.schedule_verification_inspection(p_id uuid,p_scheduled_for timestamptz) returns void language plpgsql security definer set search_path='' as $$ begin if not(select private.is_admin()) or p_scheduled_for <= now() then raise exception 'Invalid schedule'; end if; update public.verification_requests set status='inspection_scheduled',scheduled_for=p_scheduled_for where id=p_id and status='assigned'; if not found then raise exception 'Assigned request not found'; end if; end; $$;
create function public.start_verification_inspection(p_id uuid) returns void language plpgsql security definer set search_path='' as $$ begin if not exists(select 1 from public.employee_assignments where verification_request_id=p_id and employee_id=auth.uid() and status in ('assigned','accepted','in_progress')) then raise exception 'Assigned inspector required'; end if; update public.verification_requests set status='inspection_in_progress',inspection_started_at=now() where id=p_id and status='inspection_scheduled'; if not found then raise exception 'Invalid transition'; end if; update public.employee_assignments set status='in_progress' where verification_request_id=p_id and employee_id=auth.uid() and status in ('assigned','accepted'); end; $$;
create function public.save_inspection_report(p_request_id uuid,p_result public.inspection_result,p_summary text,p_notes text,p_body public.condition_rating,p_tyres public.condition_rating,p_interior public.condition_rating,p_engine public.condition_rating,p_brakes public.condition_rating,p_mileage_checked boolean,p_registration_checked boolean) returns uuid language plpgsql security definer set search_path='' as $$ declare v_id uuid; begin if not exists(select 1 from public.employee_assignments where verification_request_id=p_request_id and employee_id=auth.uid() and status='in_progress') then raise exception 'Assigned inspector required'; end if; insert into public.inspection_reports(verification_request_id,inspector_id,overall_result,summary,inspector_notes,body_condition,tyre_condition,interior_condition,engine_condition,brakes_condition,mileage_checked,registration_checked) values(p_request_id,auth.uid(),p_result,p_summary,p_notes,p_body,p_tyres,p_interior,p_engine,p_brakes,p_mileage_checked,p_registration_checked) on conflict(verification_request_id) do update set overall_result=excluded.overall_result,summary=excluded.summary,inspector_notes=excluded.inspector_notes,body_condition=excluded.body_condition,tyre_condition=excluded.tyre_condition,interior_condition=excluded.interior_condition,engine_condition=excluded.engine_condition,brakes_condition=excluded.brakes_condition,mileage_checked=excluded.mileage_checked,registration_checked=excluded.registration_checked returning id into v_id; return v_id; end; $$;
create function public.submit_inspection_report(p_request_id uuid) returns void language plpgsql security definer set search_path='' as $$ begin if not exists(select 1 from public.employee_assignments where verification_request_id=p_request_id and employee_id=auth.uid() and status='in_progress') then raise exception 'Assigned inspector required'; end if; if not exists(select 1 from public.inspection_reports where verification_request_id=p_request_id and inspector_id=auth.uid() and overall_result is not null and char_length(trim(coalesce(summary,''))) >= 20 and body_condition is not null and tyre_condition is not null and engine_condition is not null) then raise exception 'Complete the report before submission'; end if; update public.inspection_reports set submitted_at=now() where verification_request_id=p_request_id; update public.verification_requests set status='report_submitted',report_submitted_at=now() where id=p_request_id and status='inspection_in_progress'; if not found then raise exception 'Invalid transition'; end if; end; $$;
create function public.finalise_verification(p_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare v_car uuid; begin if not(select private.is_admin()) then raise exception 'Admin access required'; end if; select car_id into v_car from public.verification_requests where id=p_id and status='report_submitted'; if not found or not exists(select 1 from public.inspection_reports where verification_request_id=p_id and submitted_at is not null) then raise exception 'Submitted report required'; end if; update public.verification_requests set status='completed',completed_at=now() where id=p_id; update public.employee_assignments set status='completed',completed_at=now() where verification_request_id=p_id and status='in_progress'; if v_car is not null then update public.cars set is_verified=true,verified_at=now(),verified_verification_request_id=p_id where id=v_car and status='active'; end if; end; $$;

drop policy if exists "Customers read own verification requests" on public.verification_requests;
drop policy if exists "Customers create own verification requests" on public.verification_requests;
create policy "Customers read own verification requests" on public.verification_requests for select to authenticated using (requested_by=auth.uid() or (select private.is_admin()) or exists(select 1 from public.employee_assignments ea where ea.verification_request_id=id and ea.employee_id=auth.uid() and ea.status in ('assigned','accepted','in_progress')));
create policy "Admins read reports" on public.inspection_reports for select to authenticated using ((select private.is_admin()) or exists(select 1 from public.verification_requests v where v.id=verification_request_id and v.requested_by=auth.uid() and v.status='completed') or inspector_id=auth.uid());
create policy "Assigned inspectors manage report images" on public.inspection_report_images for all to authenticated using ((select private.is_admin()) or exists(select 1 from public.inspection_reports r join public.employee_assignments ea on ea.verification_request_id=r.verification_request_id where r.id=inspection_report_id and ea.employee_id=auth.uid() and ea.status='in_progress')) with check ((select private.is_admin()) or exists(select 1 from public.inspection_reports r join public.employee_assignments ea on ea.verification_request_id=r.verification_request_id where r.id=inspection_report_id and ea.employee_id=auth.uid() and ea.status='in_progress'));
create policy "Authorised report images can be read" on public.inspection_report_images for select to authenticated using ((select private.is_admin()) or exists(select 1 from public.inspection_reports r join public.verification_requests v on v.id=r.verification_request_id where r.id=inspection_report_id and ((r.inspector_id=auth.uid() and v.status in ('inspection_in_progress','report_submitted')) or (v.requested_by=auth.uid() and v.status='completed'))));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('inspection-images','inspection-images',false,10485760,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=10485760,allowed_mime_types=array['image/jpeg','image/png','image/webp'];
create policy "Assigned inspectors manage inspection storage" on storage.objects for all to authenticated using (bucket_id='inspection-images' and ((select private.is_admin()) or exists(select 1 from public.inspection_reports r join public.employee_assignments ea on ea.verification_request_id=r.verification_request_id where r.id=(storage.foldername(name))[2]::uuid and ea.employee_id=auth.uid() and ea.status='in_progress'))) with check (bucket_id='inspection-images' and ((select private.is_admin()) or exists(select 1 from public.inspection_reports r join public.employee_assignments ea on ea.verification_request_id=r.verification_request_id where r.id=(storage.foldername(name))[2]::uuid and ea.employee_id=auth.uid() and ea.status='in_progress')));
create policy "Completed report images are readable" on storage.objects for select to authenticated using (bucket_id='inspection-images' and exists(select 1 from public.inspection_report_images i join public.inspection_reports r on r.id=i.inspection_report_id join public.verification_requests v on v.id=r.verification_request_id where i.storage_path=name and ((v.requested_by=auth.uid() and v.status='completed') or r.inspector_id=auth.uid() or (select private.is_admin()))));
revoke all on function public.create_verification_request(uuid,text,text,text,integer,text,text,text,text,text,date,time,text), public.cancel_own_verification_request(uuid,text), public.confirm_verification_request(uuid), public.assign_verification_inspector(uuid,uuid), public.schedule_verification_inspection(uuid,timestamptz), public.start_verification_inspection(uuid), public.save_inspection_report(uuid,public.inspection_result,text,text,public.condition_rating,public.condition_rating,public.condition_rating,public.condition_rating,public.condition_rating,boolean,boolean), public.submit_inspection_report(uuid), public.finalise_verification(uuid) from public;
grant execute on function public.create_verification_request(uuid,text,text,text,integer,text,text,text,text,text,date,time,text), public.cancel_own_verification_request(uuid,text), public.confirm_verification_request(uuid), public.assign_verification_inspector(uuid,uuid), public.schedule_verification_inspection(uuid,timestamptz), public.start_verification_inspection(uuid), public.save_inspection_report(uuid,public.inspection_result,text,text,public.condition_rating,public.condition_rating,public.condition_rating,public.condition_rating,public.condition_rating,boolean,boolean), public.submit_inspection_report(uuid), public.finalise_verification(uuid) to authenticated;
