create table public.admin_audit_logs(id uuid primary key default gen_random_uuid(),admin_id uuid not null references public.profiles(id) on delete restrict,action text not null check(char_length(action) between 1 and 120),entity_type text not null check(char_length(entity_type) between 1 and 80),entity_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.admin_audit_logs enable row level security;
create policy "Admins read audit logs" on public.admin_audit_logs for select to authenticated using ((select private.is_admin()));
create index admin_audit_logs_created_idx on public.admin_audit_logs(created_at desc);
create function public.set_staff_role(p_user_id uuid,p_make_inspector boolean) returns void language plpgsql security definer set search_path='' as $$ begin if not(select private.is_admin()) then raise exception 'Admin access required'; end if; if p_make_inspector then update public.profiles set role='inspector' where id=p_user_id and role='customer'; if not found then raise exception 'Only customers can be promoted'; end if; else if exists(select 1 from public.employee_assignments where employee_id=p_user_id and status in('assigned','accepted','in_progress')) then raise exception 'Reassign active work before demotion'; end if; update public.profiles set role='customer' where id=p_user_id and role='inspector'; if not found then raise exception 'Only inspectors can be demoted'; end if; end if; insert into public.admin_audit_logs(admin_id,action,entity_type,entity_id) values(auth.uid(),case when p_make_inspector then 'staff_promoted' else 'staff_demoted' end,'profile',p_user_id); end; $$;
create function public.set_car_featured(p_car_id uuid,p_featured boolean) returns void language plpgsql security definer set search_path='' as $$ begin if not(select private.is_admin()) then raise exception 'Admin access required'; end if; update public.cars set is_featured=p_featured where id=p_car_id; if not found then raise exception 'Listing not found'; end if; insert into public.admin_audit_logs(admin_id,action,entity_type,entity_id,metadata) values(auth.uid(),case when p_featured then 'car_featured' else 'car_unfeatured' end,'car',p_car_id,jsonb_build_object('featured',p_featured)); end; $$;
revoke all on function public.set_staff_role(uuid,boolean),public.set_car_featured(uuid,boolean) from public;
revoke execute on function public.set_staff_role(uuid,boolean),public.set_car_featured(uuid,boolean) from anon;
grant execute on function public.set_staff_role(uuid,boolean),public.set_car_featured(uuid,boolean) to authenticated;
