import Link from "next/link";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/Logo";

export function AuthShell({ mode, children }: { mode: "login" | "register"; children: React.ReactNode }) {
  const isLogin = mode === "login";
  const title = isLogin ? "Your car journey, all in one place." : "Start with confidence.";
  const copy = isLogin ? "Manage listings, bookings and verification requests whenever you need to." : "Create your free Fengxing account to buy, sell and care for your car.";
  const benefits = isLogin ? ["Manage your vehicle listings", "Track services and bookings", "Access inspection reports"] : ["List your car free of charge", "Book trusted mobile services", "Request independent inspections"];
  return <main className="min-h-[calc(100vh-160px)] bg-[#f6f8fb] px-5 py-8 sm:py-12"><div className="mx-auto grid min-h-[650px] max-w-6xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-[0_24px_70px_rgba(11,31,51,0.12)] lg:grid-cols-[.95fr_1.05fr]"><section className="relative hidden overflow-hidden bg-[#0b1f33] p-10 text-white lg:flex lg:flex-col"><div className="pointer-events-none absolute inset-0 opacity-[0.06]" style={{ backgroundImage: "repeating-linear-gradient(135deg, #fff 0, #fff 1px, transparent 1px, transparent 34px)" }} /><div className="relative"><Link href="/" aria-label="Return to Fengxing home"><Logo size="sm" /></Link></div><div className="relative my-auto"><span className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-bold uppercase tracking-[.13em] text-[#fda29b]"><ShieldCheck size={14} /> Fengxing account</span><h1 className="mt-6 max-w-md text-4xl font-bold leading-tight tracking-tight">{title}</h1><p className="mt-5 max-w-md text-base leading-7 text-slate-300">{copy}</p><ul className="mt-9 space-y-4">{benefits.map((benefit) => <li key={benefit} className="flex items-center gap-3 text-sm font-semibold text-slate-200"><CheckCircle2 size={18} className="shrink-0 text-[#7fdbca]" />{benefit}</li>)}</ul></div><p className="relative text-xs text-slate-400">Secure account access for the Fengxing marketplace.</p></section><section className="flex flex-col p-6 sm:p-10 lg:p-12"><div className="lg:hidden"><Link href="/" aria-label="Return to Fengxing home"><Logo size="sm" variant="light" /></Link></div><div className="mx-auto w-full max-w-md lg:my-auto">{children}</div></section></div></main>;
}
